version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./next.config.js:/app/next.config.js
      - ./pages/index.tsx:/app/pages/index.tsx
    ports:
      - "80:3000"